spring:
  application:
    name: lottery-app

  datasource:
    url: jdbc:mysql://13.234.242.165:3306/a1
    username: iDevice
    password: iDevice_123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
